#------------------------
#GitHub Action First Try
#Sosnin Valentin  2022.
#------------------------
name: My-First-Action

on:
  push:
    branches: 
      - '**'
    tags:
      - '**'

jobs:
  testing: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: make test
