#------------------------
#GitHub Action First Try
#Sosnin Valentin  2022.
#------------------------
name: My-First-Action

on:
  push:
    branches: 
      - '**'
    tags:
      - '**'

jobs:
  testing: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        with:
          python-version: '3.x'
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          pip install poetry flake8 pytest
          make install
      - name: Lint with flake8
        run: |
          make test
      - name: Test with pytest
        run: |
          pytest